Rails:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Naming/FileName:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - describe
